# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import timezone_pb2 as timezone__pb2


class TimeZoneStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DateTime = channel.unary_unary(
                '/example.TimeZone/DateTime',
                request_serializer=timezone__pb2.TZRequest.SerializeToString,
                response_deserializer=timezone__pb2.TZReply.FromString,
                )


class TimeZoneServicer(object):
    """The greeting service definition.
    """

    def DateTime(self, request, context):
        """Sends a timezone
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TimeZoneServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DateTime': grpc.unary_unary_rpc_method_handler(
                    servicer.DateTime,
                    request_deserializer=timezone__pb2.TZRequest.FromString,
                    response_serializer=timezone__pb2.TZReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'example.TimeZone', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TimeZone(object):
    """The greeting service definition.
    """

    @staticmethod
    def DateTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/example.TimeZone/DateTime',
            timezone__pb2.TZRequest.SerializeToString,
            timezone__pb2.TZReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
